package io.infra.idea.plugin.dynamicbean.index;

import com.intellij.lang.properties.PropertiesFileType;
import com.intellij.lang.properties.IProperty;
import com.intellij.openapi.module.Module;
import com.intellij.lang.properties.psi.PropertiesFile;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.roots.ProjectFileIndex;
import com.intellij.openapi.util.Key;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.psi.PsiElement;
import com.intellij.psi.PsiFile;
import com.intellij.psi.PsiManager;
import com.intellij.psi.search.FilenameIndex;
import com.intellij.psi.search.FileTypeIndex;
import com.intellij.psi.search.GlobalSearchScope;
import com.intellij.psi.util.CachedValue;
import com.intellij.psi.util.CachedValueProvider;
import com.intellij.psi.util.CachedValuesManager;
import com.intellij.psi.util.PsiModificationTracker;
import io.infra.idea.plugin.dynamicbean.model.InfraDynamicBeanDefinition;
import io.infra.idea.plugin.dynamicbean.model.InfraDynamicBeanConfigProperty;
import io.infra.idea.plugin.dynamicbean.model.InfraDynamicBeanKind;
import io.infra.idea.plugin.dynamicbean.model.InfraDynamicBeanModel;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.yaml.YAMLFileType;
import org.jetbrains.yaml.psi.YAMLDocument;
import org.jetbrains.yaml.psi.YAMLFile;
import org.jetbrains.yaml.psi.YAMLKeyValue;
import org.jetbrains.yaml.psi.YAMLMapping;
import org.jetbrains.yaml.psi.YAMLScalar;
import org.jetbrains.yaml.psi.YAMLSequence;
import org.jetbrains.yaml.psi.YAMLSequenceItem;
import org.jetbrains.yaml.psi.YAMLValue;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.LinkedList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Scans project properties files and builds an index of dynamic beans generated by infra modules.
 */
public final class InfraDynamicBeanIndex {
    private static final Key<CachedValue<InfraDynamicBeanModel>> CACHE_KEY = Key.create("infra.idea.plugin.dynamicBeanModel");

    private InfraDynamicBeanIndex() {
    }

    public static Collection<InfraDynamicBeanDefinition> getBeans(Project project, @Nullable String typeName) {
        List<InfraDynamicBeanDefinition> definitions = new ArrayList<>();
        for (InfraDynamicBeanDefinition definition : getModel(project).getAllBeans()) {
            if (typeName == null || definition.matchesType(typeName)) {
                definitions.add(definition);
            }
        }
        return definitions;
    }

    public static Collection<InfraDynamicBeanDefinition> getBeans(Module module) {
        List<InfraDynamicBeanDefinition> definitions = new ArrayList<>();
        ProjectFileIndex fileIndex = ProjectFileIndex.getInstance(module.getProject());
        for (InfraDynamicBeanDefinition definition : getModel(module.getProject()).getAllBeans()) {
            if (belongsToModule(definition, module, fileIndex)) {
                definitions.add(definition);
            }
        }
        return definitions;
    }

    public static @Nullable InfraDynamicBeanDefinition findByName(Project project, String beanName, @Nullable String typeName) {
        InfraDynamicBeanDefinition definition = getModel(project).findByName(beanName);
        if (definition == null) {
            return null;
        }
        if (typeName == null || definition.matchesType(typeName)) {
            return definition;
        }
        return null;
    }

    public static @Nullable InfraDynamicBeanDefinition findPrimary(Project project, @Nullable String typeName) {
        if (typeName == null) {
            return null;
        }
        for (InfraDynamicBeanKind kind : InfraDynamicBeanKind.values()) {
            if (kind.supportsType(typeName)) {
                return getModel(project).findPrimary(kind);
            }
        }
        return null;
    }

    public static @Nullable InfraDynamicBeanDefinition findByNavigationProperty(Project project, IProperty property) {
        PsiFile propertiesPsi = property.getPsiElement() == null ? null : property.getPsiElement().getContainingFile();
        if (propertiesPsi == null) {
            return null;
        }
        String propertyKey = property.getKey();
        return findByNavigationLocation(project, propertiesPsi, propertyKey);
    }

    public static @Nullable InfraDynamicBeanDefinition findByNavigationLocation(Project project, PsiFile sourceFile, String propertyKey) {
        if (sourceFile == null || propertyKey == null) {
            return null;
        }
        for (InfraDynamicBeanDefinition definition : getModel(project).getAllBeans()) {
            PsiFile candidatePsi = definition.getNavigationProperty().getContainingFile();
            boolean sameFile = sourceFile.equals(candidatePsi)
                    || (sourceFile.getVirtualFile() != null
                    && candidatePsi != null
                    && sourceFile.getVirtualFile().equals(candidatePsi.getVirtualFile()));
            if (sameFile && definition.matchesPropertyKey(propertyKey)) {
                return definition;
            }
        }
        return null;
    }

    private static InfraDynamicBeanModel getModel(Project project) {
        PsiManager psiManager = PsiManager.getInstance(project);
        CachedValuesManager manager = CachedValuesManager.getManager(project);
        return manager.getCachedValue(
                psiManager,
                CACHE_KEY,
                () -> CachedValueProvider.Result.create(buildModel(project), PsiModificationTracker.MODIFICATION_COUNT),
                false
        );
    }

    private static boolean belongsToModule(InfraDynamicBeanDefinition definition, Module module, ProjectFileIndex fileIndex) {
        PsiElement propertyElement = definition.getNavigationProperty().getPsiElement();
        if (propertyElement.getContainingFile() == null || propertyElement.getContainingFile().getVirtualFile() == null) {
            return false;
        }
        return module.equals(fileIndex.getModuleForFile(propertyElement.getContainingFile().getVirtualFile()));
    }

    private static InfraDynamicBeanModel buildModel(Project project) {
        Map<String, RedisTemplateAccumulator> redisTemplates = new LinkedHashMap<>();
        Map<String, PrefixAccumulator> rocketMqProducers = new LinkedHashMap<>();
        Map<String, PrefixAccumulator> rocketMqConsumers = new LinkedHashMap<>();
        String redisPrimary = null;
        String rocketMqPrimaryProducer = null;
        String rocketMqPrimaryConsumer = null;

        Set<VirtualFile> files = new java.util.LinkedHashSet<>(FileTypeIndex.getFiles(PropertiesFileType.INSTANCE, GlobalSearchScope.projectScope(project)));
        files.addAll(FileTypeIndex.getFiles(YAMLFileType.YML, GlobalSearchScope.projectScope(project)));
        files.addAll(FilenameIndex.getAllFilesByExt(project, "yml", GlobalSearchScope.projectScope(project)));
        files.addAll(FilenameIndex.getAllFilesByExt(project, "yaml", GlobalSearchScope.projectScope(project)));
        PsiManager psiManager = PsiManager.getInstance(project);
        ProjectFileIndex fileIndex = ProjectFileIndex.getInstance(project);
        for (VirtualFile file : files) {
            if (!fileIndex.isInSource(file) && !fileIndex.isInProject(file)) {
                continue;
            }
            PsiFile psiFile = psiManager.findFile(file);
            for (InfraDynamicBeanConfigProperty property : readConfigProperties(psiFile)) {
                String key = property.getKey();
                switch (key) {
                    case "infra.redis.primary" -> {
                        redisPrimary = property.getValue();
                        continue;
                    }
                    case "infra.rocketmq.primaryProducer" -> {
                        rocketMqPrimaryProducer = property.getValue();
                        continue;
                    }
                    case "infra.rocketmq.primaryConsumer" -> {
                        rocketMqPrimaryConsumer = property.getValue();
                        continue;
                    }
                }
                collectRedisTemplate(redisTemplates, key, property);
                collectRocketMqPrefix(rocketMqProducers, key, property, "infra.rocketmq.producers.");
                collectRocketMqPrefix(rocketMqConsumers, key, property, "infra.rocketmq.consumers.");
            }
        }

        InfraDynamicBeanModel model = new InfraDynamicBeanModel();
        for (Map.Entry<String, RedisTemplateAccumulator> entry : redisTemplates.entrySet()) {
            String configName = entry.getKey();
            RedisTemplateAccumulator accumulator = entry.getValue();
            InfraDynamicBeanKind kind = accumulator.isCluster() ? InfraDynamicBeanKind.REDIS_CLUSTER_TEMPLATE : InfraDynamicBeanKind.REDIS_TEMPLATE;
            model.add(new InfraDynamicBeanDefinition(
                    kind.buildBeanName(configName),
                    configName,
                    kind,
                    accumulator.getNavigationProperty(),
                    configName.equals(redisPrimary)
            ));
        }
        for (Map.Entry<String, PrefixAccumulator> entry : rocketMqProducers.entrySet()) {
            String configName = entry.getKey();
            model.add(new InfraDynamicBeanDefinition(
                    InfraDynamicBeanKind.ROCKETMQ_PRODUCER.buildBeanName(configName),
                    configName,
                    InfraDynamicBeanKind.ROCKETMQ_PRODUCER,
                    entry.getValue().getNavigationProperty(),
                    configName.equals(rocketMqPrimaryProducer)
            ));
        }
        for (Map.Entry<String, PrefixAccumulator> entry : rocketMqConsumers.entrySet()) {
            String configName = entry.getKey();
            model.add(new InfraDynamicBeanDefinition(
                    InfraDynamicBeanKind.ROCKETMQ_CONSUMER_FACTORY.buildBeanName(configName),
                    configName,
                    InfraDynamicBeanKind.ROCKETMQ_CONSUMER_FACTORY,
                    entry.getValue().getNavigationProperty(),
                    configName.equals(rocketMqPrimaryConsumer)
            ));
        }
        return model;
    }

    private static List<InfraDynamicBeanConfigProperty> readConfigProperties(@Nullable PsiFile psiFile) {
        if (psiFile instanceof PropertiesFile propertiesFile) {
            List<InfraDynamicBeanConfigProperty> result = new ArrayList<>();
            for (IProperty property : propertiesFile.getProperties()) {
                if (property.getKey() != null) {
                    result.add(new InfraDynamicBeanConfigProperty(property.getKey(), property.getValue(), property.getPsiElement()));
                }
            }
            return result;
        }
        if (psiFile instanceof YAMLFile yamlFile) {
            return readYamlProperties(yamlFile);
        }
        return Collections.emptyList();
    }

    private static List<InfraDynamicBeanConfigProperty> readYamlProperties(YAMLFile yamlFile) {
        List<InfraDynamicBeanConfigProperty> result = new ArrayList<>();
        for (YAMLDocument document : yamlFile.getDocuments()) {
            YAMLValue topLevel = document.getTopLevelValue();
            if (topLevel instanceof YAMLMapping mapping) {
                for (YAMLKeyValue keyValue : mapping.getKeyValues()) {
                    collectYamlKeyValue(keyValue, result);
                }
            }
        }
        return result;
    }

    private static void collectYamlKeyValue(YAMLKeyValue keyValue, List<InfraDynamicBeanConfigProperty> result) {
        String key = buildYamlPropertyKey(keyValue);
        if (key != null && !key.isBlank()) {
            result.add(new InfraDynamicBeanConfigProperty(key, readYamlScalarValue(keyValue), keyValue));
        }
        YAMLValue value = keyValue.getValue();
        if (value == null) {
            return;
        }
        if (value instanceof YAMLMapping mapping) {
            for (YAMLKeyValue nested : mapping.getKeyValues()) {
                collectYamlKeyValue(nested, result);
            }
            return;
        }
        if (value instanceof YAMLSequence sequence) {
            for (YAMLSequenceItem item : sequence.getItems()) {
                YAMLValue itemValue = item.getValue();
                if (itemValue instanceof YAMLMapping itemMapping) {
                    for (YAMLKeyValue nested : itemMapping.getKeyValues()) {
                        collectYamlKeyValue(nested, result);
                    }
                }
            }
        }
    }

    private static @Nullable String readYamlScalarValue(YAMLKeyValue keyValue) {
        YAMLValue value = keyValue.getValue();
        if (value instanceof YAMLScalar scalar) {
            return scalar.getTextValue();
        }
        return null;
    }

    private static @Nullable String buildYamlPropertyKey(YAMLKeyValue keyValue) {
        LinkedList<String> segments = new LinkedList<>();
        YAMLKeyValue cursor = keyValue;
        while (cursor != null) {
            String segment = cursor.getKeyText();
            if (segment == null || segment.isBlank()) {
                return null;
            }
            segments.addFirst(segment);
            cursor = com.intellij.psi.util.PsiTreeUtil.getParentOfType(cursor, YAMLKeyValue.class, true, YAMLFile.class);
        }
        return String.join(".", segments);
    }

    private static void collectRedisTemplate(Map<String, RedisTemplateAccumulator> templates, String key, InfraDynamicBeanConfigProperty property) {
        String prefix = "infra.redis.template.";
        if (!key.startsWith(prefix)) {
            return;
        }
        String remaining = key.substring(prefix.length());
        int separator = remaining.indexOf('.');
        if (separator == 0) {
            return;
        }
        String templateName = separator < 0 ? remaining : remaining.substring(0, separator);
        String suffix = separator < 0 ? "" : remaining.substring(separator + 1);
        RedisTemplateAccumulator accumulator = templates.computeIfAbsent(templateName, unused -> new RedisTemplateAccumulator());
        accumulator.record(suffix, property);
    }

    private static void collectRocketMqPrefix(Map<String, PrefixAccumulator> holders, String key, InfraDynamicBeanConfigProperty property, String prefix) {
        if (!key.startsWith(prefix)) {
            return;
        }
        String remaining = key.substring(prefix.length());
        int separator = remaining.indexOf('.');
        if (separator <= 0) {
            return;
        }
        String configName = remaining.substring(0, separator);
        holders.computeIfAbsent(configName, unused -> new PrefixAccumulator()).record(property);
    }

    private static class PrefixAccumulator {
        private InfraDynamicBeanConfigProperty firstProperty;
        private InfraDynamicBeanConfigProperty preferredProperty;

        void record(InfraDynamicBeanConfigProperty property) {
            if (firstProperty == null) {
                firstProperty = property;
            }
            String key = property.getKey();
            if (preferredProperty == null && key != null && (key.endsWith(".namesrvAddr") || key.endsWith(".producerGroup") || key.endsWith(".consumerGroup"))) {
                preferredProperty = property;
            }
        }

        InfraDynamicBeanConfigProperty getNavigationProperty() {
            return preferredProperty != null ? preferredProperty : firstProperty;
        }
    }

    private static class RedisTemplateAccumulator {
        private InfraDynamicBeanConfigProperty firstProperty;
        private InfraDynamicBeanConfigProperty templateNameProperty;
        private InfraDynamicBeanConfigProperty modeProperty;
        private InfraDynamicBeanConfigProperty masterHostProperty;
        private InfraDynamicBeanConfigProperty clusterNodeProperty;
        private boolean cluster;

        void record(String suffix, InfraDynamicBeanConfigProperty property) {
            if (firstProperty == null) {
                firstProperty = property;
            }
            if (suffix.isEmpty()) {
                templateNameProperty = property;
                return;
            }
            if ("mode".equals(suffix)) {
                modeProperty = property;
                cluster = "cluster".equals(property.getValue());
            }
            if ("master.host".equals(suffix)) {
                masterHostProperty = property;
            }
            if (suffix.startsWith("cluster.")) {
                cluster = true;
                if (clusterNodeProperty == null) {
                    clusterNodeProperty = property;
                }
            }
        }

        boolean isCluster() {
            return cluster;
        }

        @NotNull
        InfraDynamicBeanConfigProperty getNavigationProperty() {
            if (templateNameProperty != null) {
                return templateNameProperty;
            }
            if (cluster) {
                if (modeProperty != null) {
                    return modeProperty;
                }
                if (clusterNodeProperty != null) {
                    return clusterNodeProperty;
                }
            }
            if (masterHostProperty != null) {
                return masterHostProperty;
            }
            return firstProperty;
        }
    }
}
