CREATE TABLE SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL COMMENT 'Spring Session 内部主键',
    SESSION_ID CHAR(36) NOT NULL COMMENT '浏览器会话标识',
    CREATION_TIME BIGINT NOT NULL COMMENT '会话创建时间戳（毫秒）',
    LAST_ACCESS_TIME BIGINT NOT NULL COMMENT '最后访问时间戳（毫秒）',
    MAX_INACTIVE_INTERVAL INT NOT NULL COMMENT '最大空闲时长（秒）',
    EXPIRY_TIME BIGINT NOT NULL COMMENT '会话过期时间戳（毫秒）',
    PRINCIPAL_NAME VARCHAR(100) NULL COMMENT '已认证用户名称',
    PRIMARY KEY (PRIMARY_ID),
    UNIQUE KEY UK_SPRING_SESSION_SESSION_ID (SESSION_ID),
    KEY IDX_SPRING_SESSION_EXPIRY_TIME (EXPIRY_TIME),
    KEY IDX_SPRING_SESSION_PRINCIPAL_NAME (PRINCIPAL_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Spring Session 会话主表';

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL COMMENT '会话主表内部主键',
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL COMMENT 'Session 属性名称',
    ATTRIBUTE_BYTES BLOB NOT NULL COMMENT 'Session 属性序列化内容',
    PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT FK_SPRING_SESSION_ATTRIBUTES_SESSION
        FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION (PRIMARY_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Spring Session 属性表';
