spring:
  application:
    name: infra-trace-admin
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        period: 0

server:
  port: ${TRACE_ADMIN_PORT:18090}

infra:
  trace:
    enabled: true
    report:
      enabled: false
