package io.infra.idea.plugin.dynamicbean.model;

import java.util.List;

/**
 * Supported dynamic bean kinds generated by infra modules.
 */
public enum InfraDynamicBeanKind {
    REDIS_TEMPLATE(
            "JedisTemplate",
            List.of(
                    "io.infra.structure.redis.replication.core.JedisTemplate",
                    "JedisTemplate"
            )
    ),
    REDIS_CLUSTER_TEMPLATE(
            "JedisClusterTemplate",
            List.of(
                    "io.infra.structure.redis.cluster.core.JedisClusterTemplate",
                    "JedisClusterTemplate"
            )
    ),
    ROCKETMQ_PRODUCER(
            "RocketMQProducer",
            List.of(
                    "org.apache.rocketmq.client.producer.DefaultMQProducer",
                    "DefaultMQProducer"
            )
    ),
    ROCKETMQ_CONSUMER_FACTORY(
            "RocketMQConsumerFactory",
            List.of(
                    "io.infra.structure.rocketmq.core.RocketMQConsumerFactory",
                    "io.infra.structure.rocketmq.core.DefaultRocketMQConsumerFactory",
                    "RocketMQConsumerFactory",
                    "DefaultRocketMQConsumerFactory"
            )
    );

    private final String beanSuffix;
    private final List<String> supportedTypes;

    InfraDynamicBeanKind(String beanSuffix, List<String> supportedTypes) {
        this.beanSuffix = beanSuffix;
        this.supportedTypes = supportedTypes;
    }

    public String buildBeanName(String configName) {
        return configName + beanSuffix;
    }

    public boolean supportsType(String typeName) {
        return supportedTypes.contains(typeName);
    }

    public List<String> getQualifiedTypeNames() {
        return supportedTypes.stream()
                .filter(typeName -> typeName.contains("."))
                .toList();
    }
}
