CREATE TABLE sso_user (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户唯一标识',
    username VARCHAR(128) NOT NULL COMMENT '登录用户名',
    email VARCHAR(255) NOT NULL COMMENT '用户邮箱',
    password_hash VARCHAR(255) NOT NULL COMMENT '委托密码编码后的密码哈希',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '账户是否启用：1启用，0禁用',
    PRIMARY KEY (id),
    UNIQUE KEY UK_SSO_USER_USERNAME (username),
    UNIQUE KEY UK_SSO_USER_EMAIL (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SSO 登录用户表';

CREATE TABLE sso_user_role (
    user_id BIGINT NOT NULL COMMENT '登录用户唯一标识',
    role_code VARCHAR(128) NOT NULL COMMENT '角色编码',
    PRIMARY KEY (user_id, role_code),
    CONSTRAINT FK_SSO_USER_ROLE_USER
        FOREIGN KEY (user_id) REFERENCES sso_user (id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SSO 登录用户角色关联表';

CREATE TABLE SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL COMMENT 'Spring Session 内部主键',
    SESSION_ID CHAR(36) NOT NULL COMMENT '浏览器会话标识',
    CREATION_TIME BIGINT NOT NULL COMMENT '会话创建时间戳（毫秒）',
    LAST_ACCESS_TIME BIGINT NOT NULL COMMENT '最后访问时间戳（毫秒）',
    MAX_INACTIVE_INTERVAL INT NOT NULL COMMENT '最大空闲时长（秒）',
    EXPIRY_TIME BIGINT NOT NULL COMMENT '会话过期时间戳（毫秒）',
    PRINCIPAL_NAME VARCHAR(100) NULL COMMENT '已认证用户名称',
    PRIMARY KEY (PRIMARY_ID),
    UNIQUE KEY UK_SPRING_SESSION_SESSION_ID (SESSION_ID),
    KEY IDX_SPRING_SESSION_EXPIRY_TIME (EXPIRY_TIME),
    KEY IDX_SPRING_SESSION_PRINCIPAL_NAME (PRINCIPAL_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Spring Session 会话主表';

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL COMMENT '会话主表内部主键',
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL COMMENT 'Session 属性名称',
    ATTRIBUTE_BYTES BLOB NOT NULL COMMENT 'Session 属性序列化内容',
    PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT FK_SPRING_SESSION_ATTRIBUTES_SESSION
        FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION (PRIMARY_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Spring Session 属性表';
