spring:
  application:
    name: infra-trace-service-b

server:
  port: ${TRACE_SERVICE_B_PORT:18092}

infra:
  trace:
    enabled: true
    report:
      enabled: ${TRACE_REPORT_ENABLED:true}
      url: ${TRACE_ADMIN_URL:http://127.0.0.1:18090/api/trace/spans}
      # 演示采集入参、返回值与请求头（生产可按需开关）
      capture-request-body: true
      capture-response-body: true
      capture-request-headers: true
      max-body-length: 2000

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{traceId}] [%X{spanId}] [%X{parentSpanId}] - %msg%n"
